package br.com.gusmaomatheus.vuttr.config.openapi;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeIn;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.License;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import io.swagger.v3.oas.annotations.servers.Server;

@OpenAPIDefinition(
        info = @Info(
                title = "VUTTR - Very Useful Tools to Remember",
                description = "The application is a simple repository for management with their respective names, links, directives and tags. Made for learning purposes as part of the Bossabox backend challenge (https://bossabox.notion.site/Back-end-0b2c45f1a00e4a849eefe3b1d57f23c6).",
                version = "1.0",
                contact = @Contact(
                        name = "Matheus Gusmão",
                        email = "mgusmao412@gmail.com",
                        url = "https://www.linkedin.com/in/gusmao-matheus/"
                ),
                license = @License(
                        name = "GNU (General Public License)",
                        url = "https://www.gnu.org/licenses/gpl-3.0.txt"
                )
        ),
        servers = {
                @Server(
                        description = "Local Environment",
                        url = "http://localhost:3000"
                )
        },
        security = {
                @SecurityRequirement(
                        name = "bearerAuth"
                )
        }
)
@SecurityScheme(
        name = "bearerAuth",
        description = "Bearer authentication (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. The name “Bearer authentication” can be understood as “give access to the bearer of this token.” The bearer token is a cryptic string, usually generated by the server in response to a login request.",
        scheme = "bearer",
        type = SecuritySchemeType.HTTP,
        bearerFormat = "JWT",
        in = SecuritySchemeIn.HEADER
)
public class OpenApiConfig {
}
